# packages start with those in:
# https://github.com/pangeo-data/pangeo-stacks/blob/master/base-notebook/binder/environment.yml
name: pangeo_env
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.1
  - jupyterhub=1.0
  - jupyter-server-proxy=1.1
  - nbgitpuller=0.7
  - dask=2.6
  - distributed=2.6
  - dask-kubernetes=0.10
  - dask-labextension=1.0
  - dask-gateway=0.5
  - tornado=6.0
  - bokeh=1.3
  - python-graphviz=0.13
  - pip=19.3
  - scipy
  - xarray
  - intake
  - numpy
  - s3fs
  - intake-xarray
  - rasterio
  - matplotlib

